### ISSUE TITLE
mvp: tracking issue

### ISSUE THREAD

**Issue by bondo** [bondo/survival-list#20]
Server
- [x] add db constraint - either start date or deadline required
- [x] add start date and deadline to API
- [x] filter all items endpoint on `completed_at + interval '1 day' < current_timestamp at time zone 'utc'`
- [x] add user groups (create, join, leave, delete when last user leaves)
- [x] add permission checks to db (only items created by me or in my groups) #36
- [x] save user pictures to db
- [x] add item responsible
- [x] add time estimate to tasks
- [x] #17

Client
- [x] add start date and deadline
- [x] filter based on start date, deadline and completed at (i.e. implement all views)
- [x] add responsible (display picture next to item)
- [x] create user group
- [x] join user group
- [x] leave user group (warn if last user there and it contains items)
- [x] select user group in create/edit views
- [x] select responsible in create/edit views
- [x] select time estimate in create/edit views
- [x] pull down to refetch
- [x] create/edit interface for recurring tasks
